export { default as NavbarCont } from './NavbarCont'
export { default as HeroCont } from './HeroCont'
export { default as FooterCont } from './FooterCont'
export { default as BestFoodsCont } from './BestFoodsCont'
export { default as FoodsCont } from './FoodsCont'
export { default as FoodDetailCont } from './FoodDetailCont'
export { default as CartCont } from './CartCont'
