export { default as HomeView } from './HomeView'
export { default as FoodsView } from './FoodsView'
export { default as FoodDetailView } from './FoodDetailView'
export { default as CartView } from './CartView'
export { default as NewOrderView } from './NewOrderView'
